### ISSUE TITLE
Compile with F2

### ISSUE THREAD

**Issue by Ddemon26** [adammyhre/Unity-Utils#30]
F2 is normally used for renaming, and i miss fire this command so often its kind of tilting. please consider F12 or some other F key.

**Comment by adammyhre** [comment]
You know you can reassign hotkeys under Edit > Shortcuts...

Anyway, I'll change it.

**Comment by Ddemon26** [comment]
are you speaking of changing F2 renaming key bind to something else? or changing your hotkey to another bind via settings? I'm only speaking because F2 is a global rename command for most apps, i could change it just for unity. that is my only concern with this.

**Comment by adammyhre** [comment]
I agree with you that some people might find it confusing/annoying/tilting.  I personally never use F2 to rename things in Unity, so I don't have this issue, but you opened the issue saying you misfire the command often, and it's likely that other people do this as well.  I mentioned that you can change it in Shortcuts in case you thought it was immutable.

F2 was the original key bind suggested for this on command Discord, and I agreed with that because for me, it's convenient.  I'm not going to use F12, because that's used by the FullScreen plugin which is used by many, so I've changed the default to F5.

**Comment by adammyhre** [comment]
And now, thanks to you, I've discovered the Shortcuts Api which I didn't know about before:
https://docs.unity3d.com/ScriptReference/ShortcutManagement.ShortcutManager.html

```csharp
        const string ShortcutId = "Main Menu/File/Compile";
        try {
            var newBinding = new ShortcutBinding(new KeyCombination(KeyCode.F2));
            ShortcutManager.instance.RebindShortcut(ShortcutId, newBinding);
            Debug.Log($"Shortcut {ShortcutId} rebinded to {newBinding}");
        } catch (ArgumentException) {
            Debug.LogError($"Shortcut {ShortcutId} not found");
            return;
        }
```

**Comment by Ddemon26** [comment]
> And now, thanks to you, I've discovered the Shortcuts Api which I didn't know about before: https://docs.unity3d.com/ScriptReference/ShortcutManagement.ShortcutManager.html
> 
> ```cs
>         const string ShortcutId = "Main Menu/File/Compile";
>         try {
>             var newBinding = new ShortcutBinding(new KeyCombination(KeyCode.F2));
>             ShortcutManager.instance.RebindShortcut(ShortcutId, newBinding);
>             Debug.Log($"Shortcut {ShortcutId} rebinded to {newBinding}");
>         } catch (ArgumentException) {
>             Debug.LogError($"Shortcut {ShortcutId} not found");
>             return;
>         }
> ```

This seems like a modern stream lined way of doing it, just insert the feature into the shortcuts itself. and problem solved xD

**Comment by Ddemon26** [comment]
Merry Christmas!
